spring.application.name=gateway

server.port=${SERVER_PORT:8080}

gateway.routes.cliente-service-url=${CLIENTE_SERVICE_URL:http://localhost:8081}
gateway.routes.loja-service-url=${LOJA_SERVICE_URL:http://localhost:8082}

gateway.rate-limit.habilitado=${RATE_LIMIT_HABILITADO:true}
gateway.rate-limit.capacidade=${RATE_LIMIT_CAPACIDADE:100}
gateway.rate-limit.janela=${RATE_LIMIT_JANELA:1m}
